# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LocationApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LocationApp
  pod 'Alamofire', '~> 5.4'
  pod 'SwiftyJSON', '~> 5.0'

  target 'LocationAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
